### ISSUE TITLE
Changing theme at https://seek-oss.github.io/braid-design-system/ has no visible effect.

### ISSUE THREAD

**Issue by dabrahams** [seek-oss/braid-design-system#1034]
The "Theme" menu in the upper left of the page seems to have no effect; Not in Chrome, not in Safari.

**Comment by michaeltaranto** [comment]
👋  Hey, the site itself is not themed, the selector controls the theme of the components that are documented on the site. So to see the affect you should be on a page that renders component previews, for example [Button](https://seek-oss.github.io/braid-design-system/components/Button)
