### ISSUE TITLE
Use in Vite 

### ISSUE THREAD

**Issue by KyleAMathews** [seek-oss/braid-design-system#1203]
Is this currently possible? I tried and it seems like sku is a hard dependency? I really like what y'all have built so would love to be able to use it in a project! Currently pulling out bits and pieces badly 😂

**Comment by mrm007** [comment]
Braid is currently published as source, which requires [sku](https://github.com/seek-oss/sku) to do the heavy lifting in the consuming app.

We’re actually [working on compiling Braid](https://github.com/seek-oss/braid-design-system/pull/1202) using more modern tools like Vite, Rollup and esbuild that will make Braid easier to consume in apps.

**Comment by KyleAMathews** [comment]
🔥 I'll follow that issue then!

**Comment by jahredhope** [comment]
With [Braid Design System V32](https://github.com/seek-oss/braid-design-system/releases/tag/braid-design-system%4032.0.0) this package is now pre-compiled. Reducing the requirements to align on bundling technology for a consumer.

Thanks for raising the question, I'll close this now, but please feel free to re-open if you'd like to discuss more.
