### ISSUE TITLE
Typo in examples/job-summary

### ISSUE THREAD

**Issue by piotrszymaniec** [seek-oss/braid-design-system#1298]
I didn't know where to report this, so here it is. :)

![braid-sd-examples-job-summary](https://user-images.githubusercontent.com/5377285/236700981-31383c2d-db10-40a2-b758-af7010b3884e.png)

**Comment by kuriacka** [comment]
Nice catch! I have created PR https://github.com/seek-oss/braid-design-system/pull/1299 with fix.
