### ISSUE TITLE
Is it possible to expose build-theme-related methods?

### ISSUE THREAD

**Issue by GitOfJason** [seek-oss/braid-design-system#1313]
I have reviewed the source code, and the official themes are created using methods such as makeBraidTheme and related types. Defining the values of some tokens can create a new theme. However, these methods and types are not public. I would like to know how you consider providing users with the possibility of customizing themes.

**Comment by jahredhope** [comment]
Thanks for the question. In short, we don't allow consumers to customise themes. This is a deliberate decision to avoid customisation and optimise for consistency across products.

Any changes to the theme, including adding a new theme, would be made at the system level.

This works for us, as Braid is intended for use within SEEK Group. A more general purpose design systems may want to allow more customisation.

**Comment by jahredhope** [comment]
I'll close this now, but feel free to re-open if you have another question.
