### ISSUE TITLE
Add support for Vite

### ISSUE THREAD

**Issue by farhan-helmy** [seek-oss/braid-design-system#1396]
Suggestion, currently braid design system does not work with Vite. Can we add support for Vite? I can contribute to this, I think I found some place that throws error, for example Vite uses `import.meta.env` and Braid still uses `process.env`

**Comment by askoufis** [comment]
It's on our radar to improve support for vite. It _does_ work, with a bit of effort. We likely would not replace `process.env` with `import.meta.env` as that is vite-specific API. Currently we depend on the bundler to replace `process.env.NODE_ENV` values at build-time.
