### ISSUE TITLE
Some links components broken on website

### ISSUE THREAD

**Issue by tcelestino** [seek-oss/braid-design-system#172]
There are links about some components on BRAID's website that redirect to page not found.

This links:

- [useThemeName](https://seek-oss.github.io/braid-design-system/components/useThemeName)
- [useThemeTokens](https://seek-oss.github.io/braid-design-system/components/useThemeTokens)
- [ThemeTokensConsumer](https://seek-oss.github.io/braid-design-system/components/ThemeTokensConsumer)

**Comment by markdalgleish** [comment]
This was actually fixed a while ago, but we forgot to close this issue.

Thanks for the heads up 👍
