### ISSUE TITLE
Docs for CRA setup

### ISSUE THREAD

**Issue by CarlosGines** [seek-oss/braid-design-system#475]
Since I watched Mark's talk, I just love your concept of elements without surrounding blank space. It's genius!
Do you have any plans on adding the docs for other setups apart from sku? I think it would be a really amazing to be able to use it with Create React App!

**Comment by chrbala** [comment]
Yeah, having extra setup instructions would be cool - CRA, Gatsby, Next.JS are all systems that would be great to have specific setup instructions or integrations.

**Comment by maraisr** [comment]
Afaik; it'll be up to you to figure this one out. Braid isnt meant for mass consumption: https://twitter.com/markdalgleish/status/1242720681994797056?s=20

However.

you'll need 2 things to happen to CRA. Granted I've never used CRA, so please seek docs on how to achieve these things elsewhere.

1. Have TypeScript support (as braid publishes typescript to npm)
2. Configure webpack treat plugin

then simply follow their readme to consume the library.
https://github.com/seek-oss/braid-design-system/blob/master/README.md#L39-L49

**Comment by markdalgleish** [comment]
Yep, what @maraisr said.

Are you wanting to use Braid in your own project? The docs could be clearer on this, but this is very much an in-house design system built to support our own work, not a general purpose component library. It's only open source to make it easier for us to consume, and so that others can learn from our work.

**Comment by chrbala** [comment]
For me at least, I was considering using the layout components alone, but I ended up using them as reference to make my own, as you say. Thanks for making these open source so I could look at them!

**Comment by CarlosGines** [comment]
Alright! I understand. Yes, I wanted to use Braid in my own project, it is a pity not being to use it directly in an unejected CRA.
I am doing the same as @chrbala mentioned, I am using the source as reference to create a simplified version of it!
Thank you very much for sharing it, it is a very inspiring project :) Best wishes!
