### ISSUE TITLE
How is the align prop on columns supposed to work

### ISSUE THREAD

**Issue by possibilities** [seek-oss/braid-design-system#595]
Wondering a bit about the align prop on Columns. It doesn't seem to have an effect here:

https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8BhCAbArgWwHYGcACAQ3QEsBzXAXgB1wZcAXGAJ3sPwAdiwY6Q+bKXT0AfLVyFCqDDlwSp0mQAV0vGAAsMsVoU0xKmptWAA2AAwBfQgHcyUJptOWbAekXSkbtFjyeZX3kArzUNbXRdfUMKY1MARgtrQg9JLx85f0lvILx8RRAAGhAnGGwYfAQAbUEYGABrAEFcAC8QAF1i+0dNSvgqgGYAJgt2qyA

Seems only to add justify-content: center (in my example) but there's no flexbox around it. Am I misunderstanding the intention? Thanks, I'm learning a lot from exploring this!

**Comment by markdalgleish** [comment]
The `align` prop on `Columns` aligns the `Column` elements within its container, which is useful for two scenarios:

1) When collapsing to a vertical stack on smaller screens.
2) When your column widths don't add up to 100%.

Here's a demo: https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8BhAhgJygPgDoDsACQpAZQBc0wBrQgZwAcqYBeXEAWxigEsBXDuzxFiJABIw0vfAHNCAGxgA3GPLYgALO0Jp5PGfnVgY+cjAxCCo0QHUAFicKR5AogHceUcnbpXrJACMMQgB6YX9CKAh8AHJyHSgoQj4GQnIIQgBGAAZsgFI-YiQQiSkeWXDRVAgXDnw6HT0DIxMzCxB6JmN1Og5deUsRa2ra909vdUyQrRBKiKQABXlmOxrYYId9O3IWYAA2bIBfULmqkJQa11Oii9HCDy87SenBiKKllbXzQk2Zbd2ckcToUzrcriDimC6nRTkgACI8JSeb5hCGlaRyRQqNTsGaNfSGdjGUzmV7+eyOZyuBrOZYMOgwCElSQY2FQ+pOGp0hkAIVUEDc6koAUU5G0ugJLRJ7U6zB6fXkA1mIJulzq1yqH2Mq3k63u4ye+yBv3+RuOqKGoLV+A1I3BluGWpgOr1DwmZp+MC2O2AgPNtvO1thgdGML8xQoVGowkhmBwBBAABoQN4YFw6AgANogBkwagAQXwAC8QABdZNunxZgDMACZsqXDkA

**Comment by possibilities** [comment]
Thanks!
