### ISSUE TITLE
Inline covers upper elements 

### ISSUE THREAD

**Issue by umidbekkarimov** [seek-oss/braid-design-system#685]
It's ok in Safari, but blocks click on both Chrome and Firefox, here are the examples:

* Safari Version 13.1.1 (15609.2.9.1.2)

![Jul-15-2020 11-20-58 AM](https://user-images.githubusercontent.com/4734297/87510609-52cbd580-c68d-11ea-8956-8a7db9a3d66c.gif)

* Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)

![Jul-15-2020 11-21-06 AM](https://user-images.githubusercontent.com/4734297/87510626-58c1b680-c68d-11ea-9499-6503146aa34a.gif)

* Firefox 73.0.1 (64-bit)

![Jul-15-2020 11-21-10 AM](https://user-images.githubusercontent.com/4734297/87510627-595a4d00-c68d-11ea-8744-5f7a98088ab9.gif)

* Playroom

https://seek-oss.github.io/braid-design-system/playroom/#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF4AdEAZwFtcAbR6gPkuM0yQGUAXXGADWmGnjAwqtBszYcuXJAElijEjFHjJ1ekxYhMTQqWIBNKROJ8YAJzmcFigEYBXPnwic%2BAT2zbaLk50hHzUmJ4AwmrC5MAAFACUmOSshoy2fHHUABIw3gCE1AkAvuwOjlxRhMKYdDDyFUgA9K7unmUNjkitHl6%2B-jSBwaEGkdFCsYnJqUwZWSC5BUWlnRVVNXWrii1uvWVdTSpqxDAd5dxH6pqC-oy4NqT1IPuNAAp3EgAWEIywNpifGDGT58WIAFgAHMVMAB3QhQPifcFQzBNF5dd43b6-WwAoGkEHI6FwhFI4CQ6Fo1bNS4nF7NfiCIRlZpodBlEAAGhAiJgdRoCAA2rQYDAhABBYgALxAAF1uSTEQL4IKAOwANghsuKQA

**Comment by michaeltaranto** [comment]
Fixed by https://github.com/seek-oss/braid-design-system/pull/692
