### ISSUE TITLE
Add a Navigation Component

### ISSUE THREAD

**Issue by alexander-schranz** [seek-oss/braid-design-system#892]
I'm not sure maybe I did just not found it but I'm searching for a way to have a main navigation component. Something like [UI Shell in Carbon](https://react.carbondesignsystem.com/?path=/story/ui-shell--header-base-w-navigation). Or How do you currently create a Navigation your applications?

**Comment by markdalgleish** [comment]
See https://github.com/seek-oss/braid-design-system/issues/891#issuecomment-776409546.
