### ISSUE TITLE
Button component generates invalid html

### ISSUE THREAD

**Issue by apdrsn** [seek-oss/braid-design-system#922]
Hi and thanks for this awesome design system. It inspires me a lot in my current work.

I just stumbled upon something. The `Button` component has a lot of `div`s inside it which is [invalid markup](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button).

I don't know if this is something, that you decided on internally was okay to do - then you can of course just close the issue :)
If not, would it then be an option to make typescript triggering an error if a `div` or any other block elements is used inside the `button`?

**Comment by michaeltaranto** [comment]
Fixed in v31.
